### ISSUE TITLE
Rename task generate

### ISSUE THREAD

**Issue by rost5000** [rivancic/asyncapi-generator-gradle-plugin#19]
It is better to rename the default task `generate` like [OpenApi tasks](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin#tasks). like `asyncApiGenerate`.

It is also great to define new tasks, based on OpenApi approaches (for example, with differents types of inputs)

**Comment by rivancic** [comment]
I'll rename the generate task -> asyncApiGenerate.

Do you have an idea for other handy tasks that I should expose as async generator plugin tasks?

**TODO**

Update Readme and any other reference.

**Comment by rivancic** [comment]
I see Async API has two separate projects.

First one is for managin Async API files -> https://github.com/asyncapi/cli

Second one is just generator -> https://github.com/asyncapi/generator

In my case I am wrapping only a generator and for this reason has only a asyncApiGenerator task because it doesn't contain other functionality. While I may combine both the Async API CLI and Generator into one plugin.
